<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Biblioteca de Autores Venezolanas en Dominio Público')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
      <div class="container">
        <div class="row">
          <!-- Page header -->
          <div class="col-md-4">
            <div class="app-caption">dp-<i>venezuela</i></div>
          </div>
        </div>
        <div class="col-md-12">
          <p>Biblioteca de autores venezolanos bajo dominio público.</p>
        </div>
        <div class="row">
          <div class="col-md-12">
            <!-- Page content placeholder -->
            <?= $this->content; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <hr>
            <p><?= date('Y') ?> por Dominio Público Venezuela.</p>
        </div>
      </div> <!-- /container -->
      <?php echo $this->inlineScript() ?>
    </body>
</html>
