<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Biblioteca de Autores Venezolanas en Dominio Público')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
      <div class="container">
        <div class="row">
            <!-- <img src="http://etc.usf.edu/clipart/2600/2682/filigree-banner_17_lg.gif"> -->
            <h4 align="center">BIBLIOTECA DE AUTORES VENEZOLANOS BAJO <b>DOMINIO PÚBLICO<b>.</h4>
        </div>
        <div class="row">
          <div class="col-md-12">
            <!-- Page content placeholder -->
            <?= $this->content; ?>
          </div>
        </div>
        <div class="row footer">
          <div class="col-md-12">
            <hr>
            <p><?= date('Y') ?> por Dominio Público Venezuela.  <a href="mailto:contacto@dominiopublico.org.ve?subject=[dp-ve]">Contactar</a>
          </div>
        </div>
      </div> <!-- /container -->
      <?php echo $this->inlineScript() ?>
    </body>
</html>
